### ISSUE TITLE
Order progress tracker

### ISSUE THREAD

**Issue by IncognitoJam** [campus-bites/campus-bites-vue#64]
A feature which is found on competitor services is the ability to track order progress as a customer. We should create an order tracker showing the order steps and display where in the list the courier has reached.

**Stages of order:**
  - Assigned courier ("Your courier is..")
  - Ordered food ("Order placed at ..., ETA: ... mins")
  - Collected food ("Your courier is on their way! ETA: ... mins")
  - Delivered ("Order completed")

**Preparation:**
  - [ ] Finalise order stages
  - [ ] Develop order tracker mockup
  - [ ] Write an order progress specification

**Work:**
  - [ ] Implement order progress updater on Courier dashboard
  - [ ] Implement order progress tracker component

**Stretch goals:**
  - [ ] Show courier location
  - [ ] Estimate delivery time dynamically (using data from other orders)
